spring:
  datasource:
    url: jdbc:mysql://192.168.81.45:3308/tonoyo?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root***
    password: rootPass***
  mvc:
    favicon:
      enabled: false