mail:
  fromMail:
    addr: xxoo@xxoo.com
spring:
  datasource:
    url: jdbc:mysql://tonoyo-test-db.coeenstqrhsg.us-east-2.rds.amazonaws.com:3306/tonoyo?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: longchamp
    password: longchamp
  mvc:
    favicon:
      enabled: false
  rabbitmq:
    host: 192.168.81.18
    port: 5672
    username: test
    password: test

  mail:
    host: 192.168.81.18
    port: 25
    username: xxoo@xxoo.com
    password: xxoo
    default-encoding: UTF-8