package jp.co.drm.base.integration.mybatis.dao;

import java.util.List;
import jp.co.drm.base.integration.mybatis.entity.People;
import jp.co.drm.base.integration.mybatis.entity.PeopleExample;
import org.apache.ibatis.annotations.Param;

public interface PeopleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    long countByExample(PeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int deleteByExample(PeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int deleteByPrimaryKey(Long personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int insert(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int insertSelective(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    List<People> selectByExample(PeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    People selectByPrimaryKey(Long personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int updateByExampleSelective(@Param("record") People record, @Param("example") PeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int updateByExample(@Param("record") People record, @Param("example") PeopleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int updateByPrimaryKeySelective(People record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table people
     *
     * @mbg.generated Wed Jul 12 14:08:25 JST 2017
     */
    int updateByPrimaryKey(People record);
}