package jp.co.drm.base.integration.mybatis.entity;

import java.io.Serializable;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotBlank;

public class Person implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.person_id
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    private Long personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.first_name
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
	@NotBlank
	@Size(max = 20)
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.last_name
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table person
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.person_id
     *
     * @return the value of person.person_id
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    public Long getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.person_id
     *
     * @param personId the value for person.person_id
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.first_name
     *
     * @return the value of person.first_name
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.first_name
     *
     * @param firstName the value for person.first_name
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.last_name
     *
     * @return the value of person.last_name
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.last_name
     *
     * @param lastName the value for person.last_name
     *
     * @mbg.generated Thu Jul 13 14:13:22 JST 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}